name: symmetric_difference
description:
  This Dart package provides efficient set operations (union, intersection, difference)
  for multiple collections, replacing manual methods with a single, robust solution.

version: 2.0.1
repository: https://github.com/ScorlyFly/Symmetric_difference

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

license: MIT
