name: symmetric_difference
description: This library only works with the specified data type.
  This library can find unique data from more than 2 structures, in other words,
  it is a complete replacement for imperfect methods in the dart language.
  Programming differences and intersections

version: 2.0.1
repository: https://github.com/ScorlyFly/Symmetric_difference

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

license: MIT
